/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package driverhistory;
//Importing java libraries
import javax.swing.table.DefaultTableModel;
import java.lang.reflect.*;




/**
 *
 * @author marianalicona
 */
public class RootInsuranceDriverHistory extends javax.swing.JFrame {
    private Object DateTimeFormatter;
    private Object tabla;
    private Object object;

    /**
     * Creates new form RootInsuranceDriverHistory
     */
    public RootInsuranceDriverHistory() {
        initComponents();
        Table.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Report_Button1 = new javax.swing.JButton();
        Report_Button2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSlider1 = new javax.swing.JSlider();
        Start_Input1 = new javax.swing.JTextField();
        Logo = new javax.swing.JLabel();
        Program_Tittle = new javax.swing.JLabel();
        Separator_Header = new javax.swing.JSeparator();
        Driver_Name = new javax.swing.JLabel();
        Start_Time = new javax.swing.JLabel();
        Stop_Time = new javax.swing.JLabel();
        Name_Input = new javax.swing.JTextField();
        Distance_Miles = new javax.swing.JLabel();
        Miles_Input = new javax.swing.JTextField();
        Separator_Results = new javax.swing.JSeparator();
        Clear_Button = new javax.swing.JButton();
        New_Data = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        Stop_Input = new javax.swing.JFormattedTextField();
        Start_Input = new javax.swing.JFormattedTextField();

        Report_Button1.setBackground(new java.awt.Color(255, 102, 0));
        Report_Button1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Report_Button1.setText("View Report");

        Report_Button2.setBackground(new java.awt.Color(255, 102, 0));
        Report_Button2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Report_Button2.setText("Report");
        Report_Button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Report_Button2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Root Insurance Driver's History");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/driverhistory/Root-Logo.png"))); // NOI18N

        Program_Tittle.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        Program_Tittle.setText("Driver's History System");

        Driver_Name.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Driver_Name.setText("Driver Name:");

        Start_Time.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Start_Time.setText("Start Time:");

        Stop_Time.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Stop_Time.setText("Stop Time:");

        Name_Input.setToolTipText("Hello");
        Name_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_InputActionPerformed(evt);
            }
        });
        Name_Input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Name_InputKeyPressed(evt);
            }
        });

        Distance_Miles.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Distance_Miles.setText("Distance (mi):");

        Miles_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Miles_InputActionPerformed(evt);
            }
        });

        Clear_Button.setBackground(new java.awt.Color(255, 102, 0));
        Clear_Button.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        Clear_Button.setText("Clear");
        Clear_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Clear_ButtonActionPerformed(evt);
            }
        });

        New_Data.setBackground(new java.awt.Color(255, 102, 0));
        New_Data.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        New_Data.setText("New Driver");
        New_Data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_DataActionPerformed(evt);
            }
        });

        Table.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Start Time", "Stop Time", "Miles", "Speed mph"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(Table);
        if (Table.getColumnModel().getColumnCount() > 0) {
            Table.getColumnModel().getColumn(0).setResizable(false);
            Table.getColumnModel().getColumn(1).setResizable(false);
            Table.getColumnModel().getColumn(2).setResizable(false);
            Table.getColumnModel().getColumn(3).setResizable(false);
            Table.getColumnModel().getColumn(4).setResizable(false);
        }

        try {
            Stop_Input.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Stop_Input.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                Stop_InputCaretUpdate(evt);
            }
        });
        Stop_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Stop_InputActionPerformed(evt);
            }
        });

        try {
            Start_Input.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Start_Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Start_InputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Separator_Header)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Separator_Results, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Distance_Miles)
                                        .addGap(2, 2, 2)
                                        .addComponent(Miles_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 59, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Start_Time)
                                        .addGap(18, 18, 18)
                                        .addComponent(Start_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Stop_Time)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(New_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Stop_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(140, 140, 140))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Driver_Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 283, Short.MAX_VALUE)
                .addComponent(Clear_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Program_Tittle)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59))))
                    .addComponent(jSeparator1)))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Program_Tittle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator_Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Driver_Name)
                    .addComponent(Name_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stop_Time)
                    .addComponent(Start_Time)
                    .addComponent(Start_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Stop_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Distance_Miles)
                    .addComponent(Miles_Input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(New_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Separator_Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Clear_Button)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Name_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_InputActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_Name_InputActionPerformed

    private void Miles_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Miles_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Miles_InputActionPerformed

    private void Clear_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Clear_ButtonActionPerformed
        // TODO add your handling code here:
        //Clear Button Functionality: Overwrite existing text using a blank.
        Name_Input.setText("");
        Start_Input.setText("");
        //Stop_Input.setText("");
        Miles_Input.setText("");
    }//GEN-LAST:event_Clear_ButtonActionPerformed

    private void Name_InputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Name_InputKeyPressed
        // TODO add your handling code here:
        //Moving to next input by pressing enter.
        int key=evt.getKeyCode();
         if (key==10) { Start_Input.requestFocus();
         }
    }//GEN-LAST:event_Name_InputKeyPressed

    private void Report_Button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Report_Button2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Report_Button2ActionPerformed

    private void New_DataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_DataActionPerformed
        // TODO add your handling code here:
        String TimeOne= (Start_Input.getText());
         String NumericValueOne = TimeOne.replace(":", "");
         int numberOne = Integer.parseInt(NumericValueOne);
         //Time Control Two
         String TimeTwo = (Stop_Input.getText());
         String NumericValueTwo = TimeTwo.replace(":", "");
        int numberTwo = Integer.parseInt(NumericValueTwo);
        int ConversionMin = 0;
        int ConversionMin2 = 0;

         //Calculate time
         ConversionMin = (numberOne/100)* 60;
         ConversionMin2 = (numberTwo/100)* 60;
         float Calculator = (ConversionMin2-ConversionMin)/60;
         //Calculate Spedd S= D/T (miles /hrs)
            float Miles, Speed;
              Miles = Float.parseFloat(Miles_Input.getText());
            int roundmiles = (int)Math.round(Miles);
            Speed = Miles/Calculator;
            int value = (int)Math.round(Speed);
    DefaultTableModel model = (DefaultTableModel) Table.getModel();

    Object [] fila=new Object[5];

     fila [0]=Name_Input.getText();

     fila [1]=Start_Input.getText(); //REFIRIENDO LOS CAMPOS DE TEXTO A LA TABLA

     fila [2]=Stop_Input.getText();

     fila [3]=Miles_Input.getText();

     fila [4]= value;

     model.addRow(fila); //Method to add a row
    //Table.setModel(modelo);//
    Table.setModel(model);  //Add data to tale


    }//GEN-LAST:event_New_DataActionPerformed

    private void Stop_InputCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_Stop_InputCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop_InputCaretUpdate

    private void Start_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Start_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Start_InputActionPerformed

    private void Stop_InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Stop_InputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Stop_InputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RootInsuranceDriverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RootInsuranceDriverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RootInsuranceDriverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RootInsuranceDriverHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RootInsuranceDriverHistory().setVisible(true);
            }
        });




    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear_Button;
    private javax.swing.JLabel Distance_Miles;
    private javax.swing.JLabel Driver_Name;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField Miles_Input;
    private javax.swing.JTextField Name_Input;
    private javax.swing.JButton New_Data;
    private javax.swing.JLabel Program_Tittle;
    private javax.swing.JButton Report_Button1;
    private javax.swing.JButton Report_Button2;
    private javax.swing.JSeparator Separator_Header;
    private javax.swing.JSeparator Separator_Results;
    private javax.swing.JFormattedTextField Start_Input;
    private javax.swing.JTextField Start_Input1;
    private javax.swing.JLabel Start_Time;
    private javax.swing.JFormattedTextField Stop_Input;
    private javax.swing.JLabel Stop_Time;
    private javax.swing.JTable Table;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void showUsersInJTable(String query) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void Report_ButtonActionPerformed() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
